name: Collect Google Maps Traffic

on:
  schedule:
    - cron: '0 * * * *'  # Her saat başı çalışır (UTC)
  workflow_dispatch:

jobs:
  collect-traffic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver chromium-browser

      - name: Run traffic capture script
        run: python main.py

      - name: Commit and push new images
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add images/
          git commit -m "Add new traffic image: $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
